name: StationTwelve Photography
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0.60759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bdbec0'
    - '#fefefe'
    - '#3f3f3f'
    - '#6d6d6d'
  brandStrength: 0.5
  lightness: 0.05767766572535038
  saturation: 0.8121167875360698
  rhythmicContrast: 0.2378423879854381
purpose: []
